name: Continuous Integration

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.operating-system }}

    # Skip this job if triggered by a release PR
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && !startsWith(github.event.pull_request.head.ref, 'release-please--'))

    runs-on: ${{ matrix.operating-system }}
    continue-on-error: ${{ matrix.experimental == 'Yes' }}

    strategy:
      fail-fast: false
      matrix:
        # Only tested on non-EOL Ruby versions
        ruby: ["3.2", "3.3", "3.4", "4.0"]
        operating-system: [ubuntu-latest]
        experimental: [No]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: Install Node dependencies
        run: npm ci || npm install

      - name: Run Build
        run: bundle exec rake default
